import itertools

_lorem = itertools.cycle((
	"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
	"Donec rhoncus porttitor aliquet. Vivamus rhoncus ut velit sed pulvinar. Integer dignissim, sem vel tristique scelerisque, velit risus laoreet ex, sed tristique ante ipsum vitae dui. Nullam non faucibus eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut cursus at nulla ornare posuere. Nulla facilisi. Sed rutrum, magna a tempus sagittis, purus elit vehicula urna, et fermentum nibh dolor et urna. In faucibus eget enim non consequat. Nullam et interdum dolor, sed pharetra arcu. In hac habitasse platea dictumst. Duis sed ligula fermentum, convallis ipsum eu, elementum magna. Nullam fermentum augue et lectus semper facilisis.",
	"Curabitur porttitor dolor ut turpis maximus rhoncus. Quisque porttitor nisl scelerisque bibendum venenatis. Nulla pharetra venenatis odio in molestie. Maecenas posuere venenatis tincidunt. Aenean et ante sit amet est pellentesque ultrices varius nec dui. Nunc pharetra libero sapien, et consequat sapien laoreet molestie. Suspendisse ipsum lectus, viverra sed tristique at, pulvinar at leo. Nunc maximus fringilla commodo. Aliquam molestie consequat lacus a tempus. Donec placerat magna in vulputate lacinia. Donec venenatis rutrum tincidunt. Sed lacinia, urna et euismod egestas, ipsum lectus viverra tortor, eget ultrices est lacus at mauris. Phasellus pretium ultrices nunc, eget placerat nulla venenatis sit amet. Aenean volutpat, felis id varius finibus, metus justo viverra est, facilisis fermentum sem augue in urna. Mauris fermentum pellentesque imperdiet. Suspendisse bibendum hendrerit pretium.",
	"In fringilla, libero sit amet pulvinar tincidunt, lacus nulla tempus lectus, id placerat libero nisi eu odio. Etiam non mattis massa. Proin et sagittis ipsum, at aliquet eros. Proin gravida elit et lacus pretium, ut rhoncus mi varius. Duis sed ipsum vitae nisl molestie laoreet vitae vitae massa. Cras finibus dui in sollicitudin convallis. Phasellus convallis hendrerit aliquam. Nullam eget odio scelerisque, ultrices velit eget, lacinia justo. Sed bibendum velit vitae felis porta, a luctus sem tristique. Vestibulum sed erat a enim aliquet dapibus vitae nec est. Sed laoreet eros quis nisi rutrum, a lacinia ipsum faucibus. Aliquam ullamcorper suscipit condimentum. In ligula turpis, vulputate ac auctor nec, pretium vitae magna. Vivamus id ipsum dignissim, egestas velit at, sagittis tellus. Fusce lobortis sed sapien sit amet finibus.",
	"Curabitur luctus, leo vitae ornare dapibus, leo dolor convallis purus, at tincidunt nibh ligula eu ex. Fusce urna libero, condimentum at feugiat vel, ultricies non nisi. Vestibulum pretium neque et massa maximus, vel imperdiet mauris efficitur. Nulla euismod augue turpis, sodales pharetra dui commodo molestie. Maecenas dictum rutrum justo, vel ullamcorper ante. Aenean sodales a lectus sit amet imperdiet. Etiam at erat vel arcu eleifend lacinia. Sed accumsan ante vitae nisi fermentum euismod. Ut ut cursus erat, sit amet luctus odio. Ut pellentesque massa nec sodales consectetur. Nam vel risus sagittis, facilisis metus et, ullamcorper diam. Suspendisse vitae arcu nisi. In faucibus lacus purus.",
	"Maecenas venenatis magna sit amet orci luctus lacinia. Phasellus dignissim sit amet turpis in aliquam. Quisque pretium massa et tellus mattis, at ultricies ipsum mollis. Aliquam id velit a massa placerat maximus. In varius ex a orci auctor gravida. Proin at augue purus. Donec ac vulputate libero. Etiam at nulla at mi lobortis iaculis vitae et ante. Duis vitae pretium quam, nec rutrum elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
	"Nullam magna nunc, molestie a finibus vel, ultricies quis velit. Etiam mattis tellus at tincidunt euismod. Pellentesque ligula orci, finibus at sapien vel, vehicula bibendum odio. Nam vel rhoncus quam. Nulla cursus id dolor eu efficitur. Aenean gravida, odio id dictum fringilla, nisi tellus hendrerit eros, eu mollis erat lacus ut lacus. Nunc vitae placerat metus. Nulla laoreet arcu nibh, condimentum placerat lectus condimentum eu. Morbi sit amet sollicitudin nibh. Fusce non magna ligula. Curabitur erat justo, sollicitudin quis porttitor nec, feugiat sed dui.",
	"Maecenas id leo sed leo cursus porttitor. Duis consequat laoreet maximus. Praesent hendrerit vulputate interdum. Nullam consectetur leo consectetur finibus iaculis. Fusce ac lectus augue. Fusce tincidunt arcu ex, sit amet elementum est lobortis ut. Suspendisse a odio sed velit congue mattis ut at mauris.",
	"Suspendisse semper, ante elementum mollis aliquet, odio nisl malesuada quam, at congue enim nulla ac neque. Nulla facilisi. Nam placerat accumsan ex a imperdiet. Donec urna eros, porta sit amet sem eu, rutrum condimentum libero. Morbi cursus sollicitudin ligula, quis volutpat est consequat a. Donec arcu nisl, tempus sit amet interdum at, lobortis id neque. Vestibulum sit amet tortor eros. Vestibulum congue eros ligula, quis sodales odio consequat non. Maecenas ante lacus, interdum quis hendrerit eget, pellentesque non risus. Morbi eu ante pretium turpis consectetur facilisis at sed neque. Morbi hendrerit feugiat hendrerit. Nunc id ante a metus ultricies rutrum. Aliquam ac pulvinar metus.",
	"Nullam sit amet tempus massa, a cursus odio. Vivamus sagittis tempor nunc non pellentesque. Nulla facilisi. Donec vulputate nec ligula eget fermentum. Sed interdum neque velit, quis tempor orci lacinia quis. Nunc nulla leo, molestie eget purus vel, egestas tincidunt ligula. Sed dignissim pretium est eu dignissim. Phasellus lectus lorem, interdum a quam id, consectetur gravida felis. Duis eu felis tincidunt, tincidunt turpis blandit, fermentum sem. Vestibulum id felis nec ante tristique convallis. Maecenas ultrices tempus pharetra. Aenean libero ligula, eleifend eget egestas et, tristique vel nisi. Pellentesque non elementum nisi.",
	"In et lectus erat. Sed et varius nibh. Proin ac dictum mauris, non egestas nisi. Vestibulum tincidunt suscipit nulla, vitae semper velit lacinia quis. Sed egestas odio ac lacus dictum laoreet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet mi non neque eleifend fringilla. Sed vel consectetur tortor, ac placerat odio. Proin placerat, metus et dapibus vehicula, risus purus finibus sem, vel scelerisque ligula leo volutpat tortor. Curabitur ultricies convallis euismod. Fusce consequat facilisis mattis. Morbi hendrerit rutrum ante, vitae feugiat felis varius sit amet. Vivamus fermentum urna velit, dictum viverra metus ultrices vel. Vivamus dapibus congue commodo.",
))

def ipsum():
	return _lorem.__next__()